version: '3.8'
services:
  app:
    container_name: crud-vehicles
    build: .
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - ./:/usr/src/app/
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=crud_vehicles
    ports:
      - '5432:5432'
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
